- src/config/Router.js
This bug was caused because privilege was getting changed in other screens when load user was called
Closes: #53
> More screen no longer has issues re-rendering. 

- src/ducks/Members.js
- src/ducks/User.js
Fixes #143 
Added a member action to change privileges
> Paidmember

- src/components/auth/RegistrationForm.js
Fixes #145 
Loads colleges json correctly
> fixed issue where colleges weren't loaded correctly

- src/components/Form.js
- src/components/event/EventDetails.js
- src/components/general/NavBar.js
- src/screens/Admin/ElectionAdmin.js
- src/screens/Committees/Committees.js
- src/screens/Election/ElectionCandidates.js
- src/screens/Election/ElectionPositions.js
- src/screens/Events/Events.js
- src/screens/General/Dashboard.js
- src/screens/General/More.js
- src/screens/User/OtherProfile.js
- src/screens/User/Profile.js
Small styling changes throughout the app. Caught up some election screens to the current theming of the app and incorporated the ButtonLayout component throughout the app.
Small styling changes and integration of new component
> Small updates

- src/ducks/Elections.js
- src/screens/Election/ElectionApplication.js
Fixes #142 
Fixed Election Application code and logic
> fixed electionApplication

- src/screens/Election/ElectionApplication.js
Fixes #
Just padding changes to Election Application screen
Styling
> Padding changes to election application screen

- src/components/elect/PositionForm.js
- src/screens/Election/ElectionApplication.js
- src/screens/General/More.js
Fixes #
Small styling changes
Styling
> Small visual changes on different screens

- android/.settings/org.eclipse.buildship.core.prefs
- android/app/.classpath
- android/app/build.gradle
- android/app/src/main/java/com/shpeucfapp/MainApplication.java
- android/settings.gradle
- package-lock.json
- package.json
- src/screens/Election/ElectionApplication.js
- src/screens/Election/ElectionBallot.js
- src/screens/User/OtherProfile.js
- src/screens/User/Profile.js
- src/utils/render.js
Fixes #
Added dependency for Fast Image component and modified android files for installation
> Fast image fixes

- src/screens/User/Profile.js
Fixes #
Fixed file path upload for profile pictures.
> Fixed profile picture upload path

- src/components/general/FilterList.js
Fixed a small issue with how the Filterlist was storing its initial value object.
> Fix Filterlist initial value bug

- src/components/forms/Form.js
- src/data/FormData.js
- src/ducks/User.js
- src/screens/User/Login.js
- src/screens/User/ResetPassword.js
Fixes #
Refactored login and reset password screens along with modifying the create user action. Created new form data and slightly modified the input form element
Refactoring
> Refactor login and reset password screens. Refactor create user action.

- src/components/general/Input.js
Refactor component, extended JSDocs from `TextInput`, and simplified props.
Refactoring
> Refactor input component

- src/components/general/Button.js
* Added button documentation
* Removed uncommon props and grouped into `extraProps`
Refactoring
> Refactor button component and add documentation

- src/components/general/NavBar.js
Refactor component by removing branches, converted to functional component.
Refactoring
> Refactor NavBar component

- src/components/general/DatePicker.js
Refactor component, mapped `PickerInput`s, and grouped props + functions.
Refactoring
> Refactor DatePicker component

- src/components/general/Avatar.js
- src/components/general/index.js
Fixes #210
* Created Avatar component to work *almost* like react-native-elements's Avatar but with our defaults and the `FastImage` component
> Create Avatar component to replace react-native-elements (1/2)

- src/components/general/ProgressBar.js
- src/components/general/index.js
Fixes #223
Added:
* component with hooks to behave like the progress dependency
* animations for loading updating progress
* documentation similar to the previous dependency
> Progress bar

- src/components/general/ListItem.js
- src/components/general/index.js
Fixes #211 
* Created ListItem to work similar to `react-native-elements`'s, except with nested components instead of props, and predefined styles for SHPE.
* Added documentation for all components using predefined props from react-native.
> Create ListItem component to replace react-native-elements (2/2)

- src/components/general/Animated.js
- src/components/general/index.js
Refactor `Animation` component to use full functionality of the React Native `Animated` API through `ref`s.
* Allows for use of additional animation functions
* Gives access to common animated components (Image, View, Text, FlatList)
> Add Animated component

- package-lock.json
- package.json
- src/components/general/Form/utils.js
- src/services/user.js
Fixes # 💯 
💯 
- [ 💯 ] Bug fix (non-breaking change that fixes an issue)
- [💯  ] My code follows the code style of this project found on [Contribution guidelines](https://github.com/SHPEUCF/shpeucfapp/wiki/Contribution-guidelines).
> Update lodash issues

- src/screens/User/Login.js
> Fix import issue for registration

- src/components/general/FilterList.js
- src/components/specialized/MemberPanel.js
- src/screens/General/Leaderboard.js
Fixes #208 
* Fixed FilterList clipping by adding flex to leaderboard `FilterList`
* Added `style` prop to `FilterList`
> Fix filterList clipping last element

- src/screens/General/Dashboard/Dashboard.js
- src/screens/General/Dashboard/index.js
- src/screens/General/More.js
- src/screens/index.js
Minor Dashbaord file reorganization.
> Reorganize Dashboard and Modal imports/exports

- src/App.js
- src/ducks/Elections.js
- src/ducks/Members.js
- src/ducks/User.js
- src/screens/Election/ElectionPositions.js
- src/services/elections.js
- src/services/members.js
- src/services/user.js
- src/services/utils.js
* Remove promises that wrapped Firebase Realtime listener functions that prevented realtime updated on changes to database.
* Created `cloneDeepWithout` function to fix firebase update errors that prevented updating when the entire object is deleted.
* Rename `changeLevels` function to `changeLevelsPosition` to account for committee levels function.
> Realtime updates

- src/components/general/TimePicker.js
- src/ducks/Events.js
- src/utils/events.js
* Refactor `TimePicker` component and add documentation
* Refactor timing functions: `convertMilitaryToStandardTime` + `convertStandardToMilitaryTime` === `converTimeTo`
> Events timing refactor

- src/components/general/CountryFlag.js
- src/components/general/index.js
- src/screens/General/Dashboard/Dashboard.js
Refactor the `CountryFlag` component to use functional components and hooks.
> Refactor countryflag component
